### ISSUE TITLE
`no function clause matching in Credo.Sources.find/1` error

### ISSUE THREAD

**Issue by lucas-nelson** [rrrene/credo#150] opened 2016-08-18 22:45 UTC
Followed the instructions in the README under 'Using Credo as stand alone'. I have a directory with a `.exs` file in it. It seems no matter what arguments I provide on the command-line, I get:

```
$ mix credo word_count.exs
** (FunctionClauseError) no function clause matching in Credo.Sources.find/1
    lib/credo/sources.ex:19: Credo.Sources.find([])
    lib/credo/cli.ex:102: Credo.CLI.require_requires/1
    lib/credo/cli.ex:94: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

This is using the tip of master (98cfdb089cb434d457cbf9ef6ac8be19a43f3d89). When I use the v0.4.8 tag, it works fine.

**Comment by rrrene** [comment] 2016-08-20 12:16
Thx for reporting!

**Comment by rrrene** [comment] 2016-08-20 16:23
@lucas-nelson Could you re-check with the current master?

**Comment by lucas-nelson** [comment] 2016-08-21 20:54
Works-for-me now. Thank you!

**Comment by jessejanderson** [comment] 2016-08-23 18:55
I'm running into this issue with just `mix credo`.

tried 0.4, 0.4.1, and 0.4.8 but they all seem to have the same issue.

**Comment by britto** [comment] 2016-08-23 18:57
@jessejanderson It's been fixed on master.

**Comment by jessejanderson** [comment] 2016-08-23 18:58
Sorry to clarify, not running standalone but including in my project.

**Comment by jessejanderson** [comment] 2016-08-23 18:59
Added `{:credo, "~> 0.4.8", only: [:dev, :test]},` to my list of deps.

**Comment by britto** [comment] 2016-08-23 19:02
@jessejanderson It seems the archived version will take precedence over de dependency one. Could you check you `mix archive` to see if `credo-0.4.8` is installed?

**Comment by jessejanderson** [comment] 2016-08-23 20:00
`mix archive` does show `credo-0.4.8` installed.

**Comment by britto** [comment] 2016-08-23 22:11
@jessejanderson That's it. The README intructs to checkout and build an archive based on master. So the archive installed displays as `0.4.8`, but it was actually built from a broken revision, ahead of `0.4.8`. In order to fix that, you'll need to either update your archive installation:

```
$ cd <my-credo-clone>
$ git checkout master
$ git pull --rebase
$ mix deps.get
$ mix archive.build
Generated archive "credo-0.4.8.ez" with MIX_ENV=dev
$ mix archive.install
Found existing archive: /Users/joao/.mix/archives/credo-0.4.8.
Are you sure you want to install archive "credo-0.4.8.ez"? [Yn] Y
* creating ~/.mix/archives/credo-0.4.8
$ cd <my-project>
$ mix credo
```

Or uninstall your archive, to use the version declared in your deps:

```
$ mix archive uninstall credo-0.4.8
$ cd <my-project>
$ mix credo
```

**Comment by rrrene** [comment] 2016-08-23 22:12
@jessejanderson I will release an update shortly!

**Comment by rrrene** [comment] 2016-08-23 22:24
@jessejanderson Could you test with `v0.4.9`?

**Comment by jessejanderson** [comment] 2016-08-23 22:28
Hmm, if I `mix deps.update credo` after changing to 0.4.9 is correctly show 0.4.9, but if I try `mix archive` it lists it as 0.4.8 still.

When I try `mix credo` I'm getting the same error message plus a warning to upgrade to 0.4.9.

**Comment by jessejanderson** [comment] 2016-08-23 22:32
@britto oops, just saw your message. I don't have a credo clone, I'm just using it in a project.

**Comment by jessejanderson** [comment] 2016-08-24 04:39
Installed credo locally and followed @britto 's instructions above and got it working. Thanks!

**Comment by rrrene** [comment] 2016-08-24 06:24
@jessejanderson Sorry, had to sleep :D

I seems the problem is that you can't have, say, Credo `v0.4.8` installed as a Mix archive and use `v0.4.9` as a dep on a project. I always run into this when I "test install" install Credo as an archive and then try to compile the master branch later.

So if you type `mix archive` and you see 

```
* credo-0.4.9
````

there now, just `mix archive uninstall credo-0.4.9` to save yourself from future trouble.

Hope this helps! :+1:

**Comment by sstern6** [comment] 2016-11-01 17:40
@rrrene can this be closed?

**Comment by rrrene** [comment] 2016-11-02 09:54
:+1:

**Closed by rrrene** 2016-11-02 09:54 UTC
Labels: Kind: Bug, Status: help wanted
