### ISSUE TITLE
- in macros are treated as operations

### ISSUE THREAD

**Issue by AndrewDryga** [rrrene/credo#144] opened 2016-08-07 16:04 UTC
This code produces Consistency errors, but there are no operations in it:

```
defmodule BSON.BinaryUtils do
  @moduledoc false

  defmacro int64 do
    quote do: signed-little-64
  end

  defmacro int32 do
    quote do: signed-little-32
  end

  defmacro int16 do
    quote do: signed-little-16
  end

  defmacro uint16 do
    quote do: unsigned-little-16
  end

  defmacro int8 do
    quote do: signed-little-8
  end

  defmacro float64 do
    quote do: float-little-64
  end

  defmacro float32 do
    quote do: float-little-32
  end

  defmacro binary(size) do
    quote do: binary-size(unquote(size))
  end
end
```

Result:

```
~/Projects/www/bsoneach(features/perfomance ✗) mix credo -a
Checking 8 source files ...

  Consistency                                                                   
┃ 
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:33:21 (BSON.BinaryUtils.binary)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:5:21 (BSON.BinaryUtils.int64)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:5:28 (BSON.BinaryUtils.int64)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:9:21 (BSON.BinaryUtils.int32)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:9:28 (BSON.BinaryUtils.int32)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:13:21 (BSON.BinaryUtils.int16)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:13:28 (BSON.BinaryUtils.int16)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:17:23 (BSON.BinaryUtils.uint16)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:17:30 (BSON.BinaryUtils.uint16)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:21:21 (BSON.BinaryUtils.int8)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:21:28 (BSON.BinaryUtils.int8)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:25:20 (BSON.BinaryUtils.float64)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:25:27 (BSON.BinaryUtils.float64)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:29:20 (BSON.BinaryUtils.float32)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       lib/bson/binary_utils.ex:29:27 (BSON.BinaryUtils.float32)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.2 seconds (0.01s to load, 0.2s running checks)
61 mods/funs, found 15 consistency issues.

Showing priority issues: ↑ ↗ →  (use `--strict` to show all issues, `--help` for options).
```

**Comment by rrrene** [comment] 2016-08-08 10:12
Thx for reporting! :+1:

**Comment by sstern6** [comment] 2016-10-19 17:59
Hey @AndrewDryga I am having trouble reproducing this, might have been fixed in a PR being merged recently?

Can you please post your configuration file?

I am assuming you are using `{Credo.Check.Consistency.SpaceAroundOperators}` to check the consistency, which would be throwing the errors?  Anything else you might be checking for that may be conflicting and causing this problem.

Though, @rrrene have found a bug related which I will open an issue for shortly.

**Comment by AndrewDryga** [comment] 2016-10-19 18:50
You can take a look at whole project (it's open source): https://github.com/Nebo15/bsoneach/blob/master/config/.credo.exs

**Comment by sstern6** [comment] 2016-10-19 21:50
Thanks @AndrewDryga and youre still getting the errors with the newest version of credo correct?

**Comment by sstern6** [comment] 2016-10-19 22:02
Thanks, i cloned the repo and I am seeing the errors in binary_utils.ex, will look into this and see if i can figure it out

**Comment by svoynow** [comment] 2016-10-19 22:14
Is there going to be any principled way to distinguish between these "non operator" uses of `-` and regular uses?

**Comment by rrrene** [comment] 2016-10-21 09:57
@svoynow I am afraid there is currently no convenient way to distinguish the two in all cases. We will have to work on that!

**Comment by roryqueue** [comment] 2016-10-26 12:58
I'm guessing this is already obvious by now, but this incorrect flagging isn't specific to macros. I had it come up for e.g. the following function pattern matching a binary:

```elixir
  defp parse_image_stats(<< @gif_89_signature,
    width::little-integer-size(16),
    height::little-integer-size(16),
    _remainder::binary >>) do
    %{ filetype: :gif,
      width: width,
      height: height }
  end
```

**Comment by svoynow** [comment] 2016-10-26 15:26
Yeah, this is a funny one. Obviously the compiler can disambiguate these, but must use more context. The consistency check is using the :elixir_tokenizer which tokenizes `foo-bar` and `foo - bar` the same way, as two identifiers and an operator. The only difference is in the offsets.
So I guess some later compiler pass must figure out that that's wrong....
I wonder if there's any way to fix this without having to use both the token stream *and* the AST But that seems complicated, having to keep track of which tokens correspond to which nodes in the AST.

**Comment by sevenseacat** [comment] 2017-02-22 09:39
It's weird because I only see it come up on some examples - usually when the pattern is not on the first line of a match.

eg.

```
# Fine
defp format_value("NPC_", "NPDT", <<skills::binary-27>>) do

# Gives warning
defp format_value("NPC_", "NPDT", <<stuff::integer, other_stuff::integer, even_more_stuff::integer,
  skills::binary-27>>) do
```

**Closed** 2017-03-07 18:13 UTC
Labels: Kind: Bug, Level: Intermediate, Status: help wanted

**Comment by sevenseacat** [comment] 2017-03-23 09:35
Still seeing this in credo 0.7.1. 

```
defmodule VariableSizes do
  defmacro long do
    quote do: signed-little-integer-size(32)
  end
  ...
```

```
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       apps/parser/lib/variable_sizes.ex:3:21 (VariableSizes.long)
┃ [C] ↗ There are spaces around operators most of the time, but not here.
┃       apps/parser/lib/variable_sizes.ex:3:28 (VariableSizes.long)
```
