### ISSUE TITLE
Sigil modifiers are interpreted as whitespace

### ISSUE THREAD

**Issue by manukall** [rrrene/credo#521] opened 2018-04-03 07:20 UTC
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 0.9.0 (tried 0.9.0-rc8, too)
* Erlang/Elixir version (`elixir -v`):
```
    Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
    Elixir 1.6.3 (compiled with OTP 19)
```

* Operating system: Linux

### What were you trying to do?
Updated Credo and ran it's checks. It fails with `There is no whitespace around parentheses/brackets most of the time, but here there is.` The line it points to looks like this: `assert xpath(feed, ~x"/rss/channel/title/text()"s) == "#{some.thing} on MyApp"`. After removing the `s` modifier, Credo passes.

### Expected outcome
Sigil modifiers should not be interpreted as whitespace.

### Actual outcome
Sigil modifiers are interpreted as whitespace.

**Comment by rrrene** [comment] 2018-04-03 09:36
Thx for reporting this Manuel!

I was able to reproduce the problem and add a failing test. :+1:

**Comment by rrrene** [comment] 2018-04-04 10:51
@manukall It turned out this was a bug in Elixir itself. 

`:elixir_tokenizer` was fixed in https://github.com/elixir-lang/elixir/commit/901752a4fec27152189b8b832ecd94595e4b9b8e which will fix this in future versions of Elixir.

Unfortunately, there's little we can do from the Credo-side of things. While providing some workaround to avoid the false positive might be possible, I am not sure we should patch Elixir bugs instead of requiring a certain Elixir version.

WDYT?

**Comment by manukall** [comment] 2018-04-04 11:40
hey, thanks for looking into it. i think not fixing this and waiting for a new elixir version is fine. we're just going to ignore the check in the affected places until then.

**Comment by rrrene** [comment] 2018-07-14 22:34
FYI: This is fixed in Elixir `v1.7.0-rc.0`.

**Comment by manukall** [comment] 2018-07-15 06:04
Thanks :+1:

**Comment by rrrene** [comment] 2018-07-30 08:49
I am closing this issue since Elixir 1.7 is officially out. Thx again for bringing this up! :+1:

**Closed by rrrene** 2018-07-30 08:49 UTC
